---
- name: Create user and copy files into user home directory
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
    - name: create files/directories in users home directory
      file:
       name: "{{e}}"
       state: "{{f}}"
...
